# Generated by Django 2.0.4 on 2018-05-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('create_time', models.CharField(max_length=64)),
                ('popular_number', models.CharField(max_length=64)),
                ('views_number', models.CharField(max_length=64)),
                ('weight', models.CharField(max_length=64)),
            ],
        ),
    ]
