# Generated by Django 2.0.4 on 2018-05-19 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180519_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2018, 5, 19, 15, 52, 32, 941829)),
        ),
    ]
