# Generated by Django 2.0.4 on 2018-05-19 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
