# Generated by Django 2.0.4 on 2018-05-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180519_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='厌笔不萧生', max_length=64),
        ),
    ]
