# Generated by Django 2.0.4 on 2018-05-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.IntegerField(db_column='article_id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(default='赵凯', max_length=32)),
                ('abstract', models.CharField(default='', max_length=64)),
                ('content', models.TextField(default='')),
                ('create_date', models.DateField(default='2018-05-14')),
                ('status', models.IntegerField()),
                ('view_number', models.IntegerField(default=0)),
                ('popular_numbers', models.IntegerField(default=0)),
                ('type', models.CharField(default='原创', max_length=16)),
            ],
        ),
    ]
