# Generated by Django 2.0.4 on 2018-05-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='top_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateField(default='2018-05-15'),
        ),
    ]
